#' MNN correction in reduced dimensions
#'
#' @param ... One or more matrices of low-dimensional representations where rows are cells and columns are dimensions.
#' Each object should contain the same number of columns, corresponding to the same dimensions.
#' These should have been generated by a single call to \code{\link{multiBatchPCA}}.
#' 
#' Alternatively, one or more \linkS4class{DataFrame} objects produced by previous calls to \code{reducedMNN}.
#' This should contain a \code{corrected} field of low-dimensional corrected coordinates,
#' along with information required for orthogonalization in the metadata.
#' @inheritParams fastMNN
#'
#' @inherit fastMNN value
#' @export
#' @importFrom BiocNeighbors KmknnParam
#' @importFrom BiocParallel SerialParam bpstart bpstop bpisup register
#' @importClassesFrom S4Vectors DataFrame
reducedMNN <- function (..., batch=NULL, k=20, restrict=NULL, ndist=3,
    merge.order=NULL, auto.merge=FALSE, auto.order=FALSE, min.batch.skip=0,
    BNPARAM=KmknnParam(), BPPARAM=SerialParam())
{
    batches <- list(...)
    if (is.null(names(batches))) {
        names(batches) <- seq_along(batches)
    } else if (anyDuplicated(names(batches))) {
        stop("names of '...' are not unique")
    }

    is.df <- vapply(batches, is, class2="DataFrame", FUN.VALUE=TRUE)
    if (any(is.df)) {
        .Deprecated(msg="re-use of 'fastMNN' outputs is deprecated")
        batches[is.df] <- lapply(batches[is.df], FUN=function(x) x$corrected)
    }

    checkBatchConsistency(for.checking, cells.in.columns=FALSE)
    restrict <- checkRestrictions(for.checking, restrict, cells.in.columns=FALSE)

    # Setting up the parallelization environment.
    old <- bpparam()
    register(BPPARAM)
    on.exit(register(old))

    if (!bpisup(BPPARAM)) {
        bpstart(BPPARAM)
        on.exit(bpstop(BPPARAM), add=TRUE)
    }

    args <- list(k=k, ndist=ndist, merge.order=merge.order, auto.merge=auto.merge, auto.order=auto.order,
        min.batch.skip=min.batch.skip, BNPARAM=BNPARAM, BPPARAM=BPPARAM)

    if (length(batches)==1L) {
        if (is.null(batch)) { 
            stop("'batch' must be specified if '...' has only one object")
        }
        divided <- divideIntoBatches(batches[[1]], batch=batch, restrict=restrict, byrow=TRUE)
        output <- do.call(.fast_mnn, c(list(batches=divided$batches, restrict=divided$restrict), args))
        output <- output[divided$reorder,,drop=FALSE]
    } else {
        output <- do.call(.fast_mnn, c(list(batches=batches, restrict=restrict), args))
    }

    rownames(output) <- rownames(output$corrected)
    output 
}
